using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JHTT
{
    public static class SynTab
    {
        /* Generated by 2016 ReVoL SYNAX */
        /* 27-09-2020 20:11:24 */

        /* Rule Length */
        public static int[] RLEN = { 0, 3, 4, 6, 7, 2, 1, 2, 2, 2, 1, 1, 1 };

        public enum TokType
        {
            OUT_START = 997,
            TOK_COMMENT,
            TOK_UNKNOWN,
            // терминалы
            TOK_EOT = 0,
            TOK_LS,
            TOK_RS,
            TOK_BOR,
            TOK_CSC,
            TOK_COMMA,
            TOK_RSC,
            TOK_TEXT,
            TOK_BAND,
            TOK_DOLLAR,
            TOK_XOR,
            TOK_LAST = TOK_XOR,
            // нетерминалы
            SYM_ROW,
            SYM_COL,
            SYM_TXT,
            SYM_STY,
            SYM_LAST = SYM_STY,
            // конец символов грамматики
        }

        public static TokType[] RSYM = new TokType[] {
                TokType.TOK_EOT, TokType.SYM_ROW, TokType.SYM_ROW, TokType.SYM_COL, TokType.SYM_COL,
                TokType.SYM_TXT, TokType.SYM_TXT, TokType.SYM_STY, TokType.SYM_STY, TokType.SYM_STY,
                TokType.SYM_STY, TokType.SYM_STY, TokType.SYM_STY };

        /* Syntax Table SYNTA (LR-analysis) */
        public static int[][] SYNTA;
        static SynTab()
        {

            SYNTA = new int[22][];
            SYNTA[0] = new int[15] { 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 };
            SYNTA[1] = new int[15] { Consts.ACC, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[2] = new int[15] { 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0 };
            SYNTA[3] = new int[15] { 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[4] = new int[15] { 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[5] = new int[15] { -1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0 };
            SYNTA[6] = new int[15] { 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[7] = new int[15] { -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[8] = new int[15] { 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[9] = new int[15] { 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[10] = new int[15] { 0, 0, 0, 0, 0, 0, 0, 13, 14, 15, 16, 0, 0, 11, 12 };
            SYNTA[11] = new int[15] { 0, 0, -3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0 };
            SYNTA[12] = new int[15] { 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[13] = new int[15] { 0, 0, -6, -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[14] = new int[15] { 0, 0, 0, 0, 0, 0, 0, -10, 14, 15, 16, 0, 0, 0, 19 };
            SYNTA[15] = new int[15] { 0, 0, 0, 0, 0, 0, 0, -11, 14, 15, 16, 0, 0, 0, 20 };
            SYNTA[16] = new int[15] { 0, 0, 0, 0, 0, 0, 0, -12, 14, 15, 16, 0, 0, 0, 21 };
            SYNTA[17] = new int[15] { 0, 0, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[18] = new int[15] { 0, 0, -5, -5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[19] = new int[15] { 0, 0, 0, 0, 0, 0, 0, -7, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[20] = new int[15] { 0, 0, 0, 0, 0, 0, 0, -8, 0, 0, 0, 0, 0, 0, 0 };
            SYNTA[21] = new int[15] { 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 0, 0 };
        }
    }
}
